apiVersion: apps/v1
kind: Deployment
metadata:
  name: texiu-deployment
  labels:
    app: texiu
spec:
  selector:
    matchLabels:
      app: texiu
  template:
    metadata:
      labels:
        app: texiu
    spec:
      containers:
      - name: texiu-api
        image: docker.io/library/texiu:1.0.0
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: texiu-loadbalancer
spec:
  selector:
    app: texiu
  ports:
    - name: http
      nodePort: 31101   # access from vps_public_ip:31101
      port: 4001        # access internal from cluster-ip
      targetPort: 80    # port of the web-api
  externalIPs:
  - 0.0.0.0 # the VPS public IP address
  type: LoadBalancer
